# RustCast config

[[shells]]
command = "/scripts/spotify/next.sh"
# Change to change the display name
icon_path = "/Applications/Spotify.app/Contents/Resources/AppIcon.icns"
alias = "Next Song"
alias_lc = "next"

[[shells]]
command = "/scripts/spotify/prev.sh"
icon_path = "/Applications/Spotify.app/Contents/Resources/AppIcon.icns"
alias = "Prev Song"
alias_lc = "prev"

[[shells]]
command = "/scripts/spotify/toggle_repeat.sh"
icon_path = "/Applications/Spotify.app/Contents/Resources/AppIcon.icns"
alias = "Toggle Repeat"
alias_lc = "repeat"

[[shells]]
command = "/scripts/spotify/prev.sh"
icon_path = "/Applications/Spotify.app/Contents/Resources/AppIcon.icns"
alias = "Toggle Shuffle"
alias_lc = "shuffle"

